# Generated by Django 4.2.13 on 2026-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
