# Generated by Django 4.2.13 on 2026-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bvn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='member',
            name='nin',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
