# Generated by Django 4.2.13 on 2026-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_bvn_member_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
