# Generated by Django 4.2.13 on 2026-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standing_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingorder',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
